project: 
  type: website
  output-dir: docs  

website:
  title: "Asmith Joseph Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      # Remove or comment out the empty project menu for now

    right:
      - icon: github
        href: "https://github.com/Asmithj/AsmithJoseph-MADA-portfolio"      

format:
  html:
    theme: cosmo
    highlight: monokai
    css: styles.css
    toc: false

